# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='pintrest_url',
            field=models.URLField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=90),
        ),
    ]
