# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 20:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('thumb', imagekit.models.fields.ProcessedImageField(upload_to='portfolios')),
                ('tags', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='media'),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='portfolio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='gallery.Portfolio'),
        ),
    ]
