# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 20:36
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180519_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='media'),
        ),
    ]
