# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-25 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='car',
            field=models.CharField(default='', max_length=50),
        ),
    ]
