# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='car',
            new_name='occupation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='colour',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='fav_artist',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='medium',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(default='', max_length=100),
        ),
    ]
