# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-03 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_images', models.ImageField(blank=True, height_field='image_height', upload_to='media/products/%d/%m/%y', width_field='image_width')),
                ('name', models.CharField(default='', max_length=180)),
                ('art_type', models.CharField(default='', max_length=30)),
                ('medium', models.CharField(default='', max_length=30)),
                ('size', models.CharField(default='', max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
