# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_product_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address_1', models.CharField(max_length=40)),
                ('address_2', models.CharField(max_length=40)),
                ('postcode', models.CharField(blank=True, max_length=15)),
                ('city', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.OrderProduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.Product')),
            ],
        ),
    ]
